### ISSUE TITLE
能否移植到 Firefox？

### ISSUE THREAD

**Issue by seiuneko** [acgotaku/GetCookies#10]
现在 Firefox 有 Web Extensions 了，获取 Cookies 的 [API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies) 也有了，请问有时间移植到 Firefox 吗？

**Comment by acgotaku** [comment]
目前只是用于签到程序 你有需求在FF上 签到？

**Comment by seiuneko** [comment]
对的 主力浏览器是 ff

**Comment by acgotaku** [comment]
代码好久没更新了，我只能说 有空弄一下

**Comment by seiuneko** [comment]
好的 谢谢
