### ISSUE TITLE
怎样才能在自己搭建的qiandao服务上使用...

### ISSUE THREAD

**Issue by woaihsw** [acgotaku/GetCookies#2]
不好意思我对js和网络一窍不通，我就是个普通的用户...

磕磕绊绊在自己的vps上搭建了服务，但是这个插件只能在qiandao.today上使用...

请问需要改哪些地方能让他在自己的网站上使用？

**Comment by acgotaku** [comment]
@woaihsw 囧 那你可以用开发者模式 载入插件 然后修改本插件的 mainfest.json 
"matches": [ "https://qiandao.today/*" ] 修改这个匹配值 到你搭建的网址

**Comment by woaihsw** [comment]
我之前尝试过了...

chrome的console打出了onload日志...

但是这并没有什么卵用...

还是会弹到chrome商店....

**Comment by acgotaku** [comment]
@woaihsw  那你把你搭建的网站告诉我 我来试试?

**Comment by woaihsw** [comment]
qiandao.zhaoting.li

多谢

**Comment by acgotaku** [comment]
@woaihsw 为什么你的上来是注册页面啊...

**Comment by acgotaku** [comment]
@woaihsw 你在网页里面嵌入一个 frame是几个意思啊....

**Comment by woaihsw** [comment]
并不知道啊...

我就是把那个项目拖到vps上然后运行了web.py啊...

**Comment by acgotaku** [comment]
@woaihsw  不知道那就不要搞了  你这个网站搭建出问题了 我插件也无能未力啊 vps 的ip是 162.255.119.251
但是搭建的实际服务在 204.44.94.62   我真心看不懂

**Comment by woaihsw** [comment]
我vps是204那个ip...

貌似是我那域名是url redirect转过去的...

我直接解析过去再试试吧...

还是谢谢你

**Comment by acgotaku** [comment]
@woaihsw 你为啥不直接解析到正确的 还跳转... 你这做法不对啊

**Comment by woaihsw** [comment]
两个字，懒+菜...

80端口被占了我就跳转8080了...

**Comment by acgotaku** [comment]
@woaihsw 你这就是态度问题了 ....

**Comment by woaihsw** [comment]
好吧好吧的确是态度问题...我去做个反代好了...

多谢

**Comment by woaihsw** [comment]
@acgotaku

**Comment by woaihsw** [comment]
@acgotaku 搞定了谢谢...

但是除了mainfest.json的改动...

background.js里也有个判断url是否包含qiandao.today...

**Comment by acgotaku** [comment]
@woaihsw 确实 谢谢你的提醒
