### ISSUE TITLE
Uncaught Error: Attempting to use a disconnected port object

### ISSUE THREAD

**Issue by eromoe** [acgotaku/GetCookies#3]
![111111](https://cloud.githubusercontent.com/assets/3938751/19061318/78973ff8-8a22-11e6-889b-0132fdee2f89.png)

port.postMessage 就出错了

因为chrome不让装修改过得crx，我直接用开发模式源码安装的，
看过去好像是有什么权限限制？导致无法连接这个port, 
chrome对象下的数据好像都获取不到

之前有成功过，很久没用，今天用了下就不行了。。。

**Comment by acgotaku** [comment]
@eromoe 你是二次开发 还是什么？ 我刚才试用了下 没啥问题啊

**Comment by acgotaku** [comment]
@eromoe 其实这个接口还是有问题的。。。 要是有人用 我其实想换个新的API对接

**Comment by eromoe** [comment]
抱歉回复迟了，我已经发现问题所在了。。。

我做的就是改了manifest.json， 加了 我的站点 `http://bwg:8923/*` （host 文件map的地址)

此时，如果在我自己的站上点 `获取cookies`，  就报上面那个错。

之前成功了，是因为之前在qiandao.today的主页上点击一次 获取cookies， 这个操作激活了扩展，然后在
我的站点上也可以使用了。。。当然关掉chrome以后又不行了。

然后我才在 background.js 里头发现有 url check:
```
tab.url.indexOf("qiandao.today") != -1
```

去掉就好了，不过为啥这里也加check？ 不是manifest.json 加一下就好了么=。=

**Comment by acgotaku** [comment]
@eromoe 分析的非常好 确实是这样 当年设计的不好 后台的background的设计是多余的
