### ISSUE TITLE
发现很多网站用这个插件获得的cookie和用Fiddler抓到的cookie不同

### ISSUE THREAD

**Issue by xuexiaokang** [acgotaku/GetCookies#4]
发现很多网站用这个插件获得的cookie和用Fiddler抓到的cookie不同，导致cookie经常都是无效的

**Comment by acgotaku** [comment]
例如？

**Comment by xuexiaokang** [comment]
@acgotaku 比如http://liangchanba.com，还有apk.tw，还有好几个网站，有一些网站又是正常的，我发现这个问题的原因是在qiandao.todady自己制作har文件的时候，直接带cookies的情况下能正常使用，然后自己想做成公共模板，最后再用助手获取cookie后输入竟然签到是不行的，于是我再次用Fiddler去抓包得到cookie去替换助手得到的cookie，竟然就行了，好几个网站都是这样，助手直接获取的对比Fiddler竟然是不一样的

**Comment by acgotaku** [comment]
获取的key不一样 还是？ 有没有截图之类的可以对比？

**Comment by xuexiaokang** [comment]
cookie里面那些信息是敏感的？我打个马赛克发上来对比下

**Comment by acgotaku** [comment]
value打个马赛克 我看到 key就行

**Comment by xuexiaokang** [comment]
![cookie](https://cloud.githubusercontent.com/assets/9048178/22768483/6d021c8a-eebd-11e6-9bff-c73b62a194ce.jpg)

**Comment by acgotaku** [comment]
好吧 你这个获取的没啥意义。。。 待会我自己抓包看看吧。。。

**Comment by acgotaku** [comment]
官方 好像没有 量产吧 这个模板？？

**Comment by xuexiaokang** [comment]
好的，不过初步对比下来好像助手获取的cookie前后都多了很多内容，中间部分应该才是需要拿来用的cookie，和fiddler的范围就一样了

**Comment by xuexiaokang** [comment]
嗯，自己做har

**Comment by acgotaku** [comment]
多了应该没影响 少了才会出问题才对。。。
你自己做的我不好测试啊 ==

**Comment by xuexiaokang** [comment]
根据群里的教程做的，我自己做了个用fiddler的cookie能正常，用助手的就不行，估计要把助手获得的cookie里前面和后面部分删除掉到，前面的PhtV_de56_saltkey值之前删除，tjpctrl值之后删除就可用

**Comment by acgotaku** [comment]
那你问问 binux  可能他更了解吧

**Comment by xuexiaokang** [comment]
没更新吧，他很久没更新了，而且har的制作是来源于fiddler，做出来的用来替换cookie的{{cookies}}，也就只会是PhtV_de56_saltkey值和tjpctrl值这中间这段的cookie

**Comment by acgotaku** [comment]
你列出来 不一样 的cookies 的key 我待会分析下 域

**Comment by xuexiaokang** [comment]
我又用同样的方法制作了http://www.right.com.cn的har，这次助手获得的cookie又是可用的，但是发现不同网站的cookie格式还真的有不同

**Comment by acgotaku** [comment]
肯定是域 不同吧
