### ISSUE TITLE
老大能否给一个详细一点的教程如何集合签到系统获取呢？

### ISSUE THREAD

**Issue by kukudemajia** [acgotaku/GetCookies#5]
首先要感谢老大能写出这个工具分享给大家
如果能把具体的方法写出来那将会让不少跟我一样的小白获益匪浅
无从下手ing
先谢谢了

**Comment by acgotaku** [comment]
安装之后就可以使用了啊？ 不需要任何多余的操作

**Comment by kukudemajia** [comment]
小白就是不懂怎么装呢
改本插件的 mainfest.json
"matches": [ "https://qiandao.today/*" ] 修改这个匹配值 到你搭建的网址
background.js里也有个判断url是否包含qiandao.today...
请问GetCookies目录放哪里呢？除了这些还有哪些要改动呢，谢谢

**Comment by acgotaku** [comment]
你是要应用到自己网站？

**Comment by kukudemajia** [comment]
是滴，没错，qiandao.today访问太慢了

**Comment by acgotaku** [comment]
那就改你说的那两处就可以了

**Comment by kukudemajia** [comment]
不行哦，默认还是跳到google商店的安装连接，提示未安装

**Comment by acgotaku** [comment]
你确定加载成功了么？
