### ISSUE TITLE
这个网站获取的cookie不完整

### ISSUE THREAD

**Issue by xuexiaokang** [acgotaku/GetCookies#6]
https://apk.tw/forum.php

**Comment by acgotaku** [comment]
就不能说具体点？

**Comment by xuexiaokang** [comment]
这是GetCookies获取的：
__cfduid=d6a1a39a590138f58w06aea6afca67ba661490084046; _uab_collina=1490084054231862070888605; _ga=GA1.2.547343545.14930084049; __utma=2000903238.547343545.1490084049.1490086212.1490152765.3; __utmc=2004090238; __utmz=200090238.14900384052.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __auc=bd99ba0115aefee436d2ac328e22; 
这是Fiddler获取的:
__cfduid=d6a1a39a590138f58w06aea6afca67ba661490084046; _uab_collina=1490084054231862070888605; _ga=GA1.2.547343545.14930084049; __utma=2000903238.547343545.1490084049.1490086212.1490152765.3; __utmc=2004090238; __utmz=200090238.14900384052.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __auc=bd99ba0115aefee436d2ac328e22; xfhP_2132_ulastactivity=0c37DhXjBrvplpDOJM5j3tuule3IcPnZw%2BWIJ80dvSCKKSdanazg; xfhP_2132_auth=e20dmetFsx4A1ZU%2BzMIrgTX5Gua9KE5E8cihggnLI4SnzGX9pR4VTJgtJrX71eNNvnyzgSGZkyyAP7cJB3Fozj3q4W7k; xfhP_2132_lastcheckfeed=1682786%7C1489077570; xfhP_2132_nofavfid=1; xfhP_2132_visitedfid=36D185; xfhP_2132_smile=1D1; xfhP_2132_sid=MqWBYe; xfhP_2132_lastact=1489093921%09home.php%09spacecp; xfhP_2132_pc_size_c=0; __asc=93b9ba2e15ab4ea0aaabc798c1e; xfhP_2132_lip=180.76.149.222%2C1489093906; xfhP_2132_sendmail=1; xfhP_2132_dsu_amupper_header=PHNwYW4gY2xhc3M9InBpcGUiPnw8L3NwYW4%2BPGEgaWQ9Im15X2FtdXBwZXIiIGhyZWY9ImphdmFzY3JpcHQ6OyIgb25jbGljaz0iYWpheGdldCgncGx1Z2luLnBocD9pZD1kc3VfYW11cHBlcjpwcGVyJmFqYXg9MSZmb3JtaGFzaD01ODFlODA4NyZ6anRlc3R0aW1lcz0xNDg5MDkzOTIxJywgJ215X2FtdXBwZXInLCAnbXlfYW11cHBlcicsICfnsL3liLDkuK0nLCAnJyxmdW5jdGlvbiAoKSB7dG9uZXBsYXllcigwKTt9KTsiPjxpbWcgc3JjPSIuL3NvdXJjZS9wbHVnaW4vZHN1X2FtdXBwZXIvaW1hZ2VzL2RrLmdpZiIgc3R5bGU9Im1hcmdpbi1ib3R0b206LTZweDsiPjwvYT4%3D; _gat=1; xfhP_2132_checkpm=1
这丢失的不是一点点啊，做了个模板，用getcookies获取的cookie怎么都登陆不了，拿Fiddler的cookie就可以登陆

**Comment by acgotaku** [comment]
都不说明域。。。简直就是耍流氓

**Comment by xuexiaokang** [comment]
什么是域，不懂啊。。。

**Comment by acgotaku** [comment]
就是这个cookie所属的范围

**Comment by xuexiaokang** [comment]
从哪里得知呢。。我就是直接获取的是https://apk.tw/的cookie，抓包抓的也是这个网页的

**Comment by acgotaku** [comment]
![screenshot from 2017-03-22 15-11-44](https://cloud.githubusercontent.com/assets/1191834/24184560/edc4986a-0f11-11e7-8255-e11677553216.png)

为啥我后台测试是正常的呢？ 你自己的操作是不是有误？？？

**Comment by xuexiaokang** [comment]
我是直接用qiandao.today网站上传模板后点击获取cookie得到的cookie就只有那么一点内容

**Comment by acgotaku** [comment]
那就有情签到大佬来给你解释解释 @binux

**Comment by xuexiaokang** [comment]
这个是Getcookie插件得到的cookie内容缺失，不是签到程序的问题吧

**Comment by acgotaku** [comment]
请问你是怎么得出的结论？ 我这边测试是没有问题的 模板设计方面可能也有缺陷，你为什么可以断定是这里的问题呢？

**Comment by xuexiaokang** [comment]
因为getcookie在整个过程中也就用来读取一次cookie，然后自动填入cookie值，而就是这获取的cookie都不完整，和模板的就没关系了

**Comment by acgotaku** [comment]
那你告诉我该怎么修复啊

**Comment by xuexiaokang** [comment]
getcookie根据什么来判断cookie的全部内容？这个判断是不是存在不完善？也就是getcookie判断__auc=bd99ba0115aefee46d2ac328e22;这里cookie就结束了，而实际上后面还有一堆内容没有被判断进来

**Comment by acgotaku** [comment]
你这说的都是废话。。。。 要是能解决就pr 不能解决就别说话了。。。。

**Comment by xuexiaokang** [comment]
你用后台测试得到的结果和直接Getcookie插件得到的结果是不是不相同，对比下应该知道了

**Comment by binux** [comment]
我用 Getcookie 得到的是完整的啊
你用 chrome 打开 devtools > Application > Cookies > https://apk.tw 截图上来

**Comment by xuexiaokang** [comment]
@binux 昨天因为这个获取不到完整cookie的问题，群里的管理员西凉同学进行了bilibili直播，在众多群友的见证下证实了GetCookie确实无法获取完整cookie，最后只能用EditThisCookie获得cookie才能用，有视频录像可以看http://live.bilibili.com/101937

**Comment by acgotaku** [comment]
你这放到文化大革命的时候 一定是一个完美的红卫兵

**Comment by xuexiaokang** [comment]
@acgotaku 因为确实有问题所以才提出的，没问题也不会专门去测试了，自己测试还不够，要更多人测试才能验证是真的有问题，所以就让大家一起参与了，毕竟大家都在用的东西，也是为了GetCookie能更完美而献计献策吧

**Comment by acgotaku** [comment]
binux说了问题 你却无视了。。。 让你截图你给个视频。。。。

**Comment by xuexiaokang** [comment]
@binux @acgotaku 刚刚才知道原来可以上传图片![qq 20170323130123](https://cloud.githubusercontent.com/assets/9048178/24232899/362565d2-0fc9-11e7-8fd9-09fa76745253.png)

**Comment by MoeGakuen** [comment]
刚才测试以下，我想，这足够完整了吧？
![2](https://cloud.githubusercontent.com/assets/16118914/24232982/e6197398-0fc9-11e7-8374-8bd3b64e0e10.png)

**Comment by xuexiaokang** [comment]
@binux @acgotaku @MoeGakuen 退出重新登录后，cookie变得更长了![qq 20170323132043](https://cloud.githubusercontent.com/assets/9048178/24233200/91245766-0fcb-11e7-930b-b8c459578013.png)

**Comment by MoeGakuen** [comment]
变长不变长没什么影响，只要有关键cookie就能登陆

**Comment by binux** [comment]
我猜是因为获取的是 http://apk.tw 所以获取不到HTTPS 的cookie？
这应该是qiandao的bug。

**Comment by xuexiaokang** [comment]
@binux 这个bug是签到程序的还是getcookie助手的呢？

**Comment by MoeGakuen** [comment]
不是说了是qiandao的吗。。
