### ISSUE TITLE
qiandao.today获取cookie时内容错了

### ISSUE THREAD

**Issue by EchoChan314** [acgotaku/GetCookies#8]
不知道是不是因为更新chrome的缘故。现在获取的内容连修改都不行。

**Comment by acgotaku** [comment]
具体点？

**Comment by EchoChan314** [comment]
获取后是这样：
![1.png](https://i.loli.net/2017/08/10/598b378d13cf3.png)

一点击就变成这样：
![2.png](https://i.loli.net/2017/08/10/598b378d13fed.png)

**Comment by EchoChan314** [comment]
应该是网站问题，在chrome无法编辑cookie输入框的内容，但是edge上就可以。
